version         : "2"
linters-settings:
  unused:
    check-exported: false

linters         :
  default : fast
  disable :
    - unused
    - nakedret
    - lll
    - depguard
    - wsl
  enable  :
    - tagalign
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block   : false
      branch-max-lines    : 2
