version: "2"
linters:
  default : fast
  disable :
    - unused
    - nakedret
    - lll
    - wsl
    - depguard
    - cyclop #dev-stage
    - gocognit #dev-stage
    - funlen #dev-stage
  enable  :
    - tagalign
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block   : false
      branch-max-lines    : 2
