package mod_db

const (
	F_key entryFieldName = "key"
	F_ver entryFieldName = "ver"

	F_type   entryFieldName = "type"
	F_status entryFieldName = "status"
	F_baseDN entryFieldName = "baseDN"

	F_uuid            entryFieldName = "uuid"
	F_dn              entryFieldName = "dn"
	F_objectClass     entryFieldName = "objectClass"
	F_creatorsName    entryFieldName = "creatorsName"
	F_createTimestamp entryFieldName = "createTimestamp"
	F_modifiersName   entryFieldName = "modifiersName"
	F_modifyTimestamp entryFieldName = "modifyTimestamp"

	F_cn                   entryFieldName = "cn"
	F_dc                   entryFieldName = "dc"
	F_description          entryFieldName = "description"
	F_destinationIndicator entryFieldName = "destinationIndicator"
	F_displayName          entryFieldName = "displayName"
	F_gidNumber            entryFieldName = "gidNumber"
	F_homeDirectory        entryFieldName = "homeDirectory"
	F_ipHostNumber         entryFieldName = "ipHostNumber"
	F_mail                 entryFieldName = "mail"
	F_member               entryFieldName = "member"
	F_memberOf             entryFieldName = "memberOf"
	F_o                    entryFieldName = "o"
	F_ou                   entryFieldName = "ou"
	F_owner                entryFieldName = "owner"
	F_sn                   entryFieldName = "sn"
	F_sshPublicKey         entryFieldName = "sshPublicKey"
	F_telephoneNumber      entryFieldName = "telephoneNumber"
	F_telexNumber          entryFieldName = "telexNumber"
	F_uid                  entryFieldName = "uid"
	F_uidNumber            entryFieldName = "uidNumber"
	F_userPKCS12           entryFieldName = "userPKCS12"
	F_userPassword         entryFieldName = "userPassword"

	F_labeledURI entryFieldName = "labeledURI"

	F_serialNumber   entryFieldName = "serialNumber"
	F_issuer         entryFieldName = "issuer"
	F_subject        entryFieldName = "subject"
	F_notBefore      entryFieldName = "notBefore"
	F_notAfter       entryFieldName = "notAfter"
	F_dnsNames       entryFieldName = "dnsNames"
	F_emailAddresses entryFieldName = "emailAddresses"
	F_ipAddresses    entryFieldName = "ipAddresses"
	F_uris           entryFieldName = "uris"
	F_isCA           entryFieldName = "isCA"
)
